version: "3"

services:

  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    networks:
      - MyNet

  dbpg:
    image: "postgres:12.1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: database
    networks:
      - MyNet

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - MyNet

networks:
    MyNet: